feat: add package install sh

diff --git a/install b/install
--- a/install
+++ b/install
@@ -30,18 +30,18 @@ matcha_exec_file="$matcha_project_dir_pre/matcha"
 #matcha 默认安装在该位置
 default_install_dir_pre="${1:-"/usr/local"}"
 #matcha 工程安装的绝对路径
-default_install_dir="$default_install_dir_pre/$matcha_directory"
+default_install_dir="${!matcha_work_dir_key:-$default_install_dir_pre/$matcha_directory}"
 #matcha 可执行文件安装的绝对路径
 default_install_matcha_exec_pre="/usr/local/bin"
 #matcha配置文件绝对路径
 properties_file_dir="$default_install_dir/$matcha_project_dir_pre/prop/properties.yml"
-
+matcha_log_dir="$default_install_dir/$matcha_project_dir_pre/log/matcha_log"
 ################################################################
 #               工程包相关
 #安装包压缩文件名称
 matcha_file_name="matcha.tar.gz"
 #校验文件名称
-check_file_name="SHA256SUMS"
+check_file_name="SHA256SUMS.txt"
 #当前安装的版本 此处由项目管理者填写，一般一个脚本只对应安装一个版本的matcha shell
 version="test"
 #工程包下载地址
@@ -58,14 +58,14 @@ function curl_matcha_file() {
   curl -JLO $curl_matcha_file_path
 
   if [[ $? != 0 ]]; then
-    echo "$matcha_file_name download failed!!! please try again"
+    echo "[${FUNCNAME[0]}] $matcha_file_name download failed!!! please try again"
     exit 1
   fi
 
   curl -JLO $check_sha256
 
   if [[ $? != 0 ]]; then
-    echo "SHA256SUMS download failed!!! please try again"
+    echo "[${FUNCNAME[0]}] SHA256SUMS download failed!!! please try again"
     exit 1
   fi
   sudo /usr/bin/dos2unix SHA256SUMS.txt
@@ -75,18 +75,16 @@ function tar_matcha_file() {
   if [[ ! -d "$matcha_directory" ]]; then
     sudo /usr/bin/mkdir "$matcha_directory"
   fi
-  sudo /usr/bin/tar -xvf "$matcha_file_name" -c "$matcha_directory"
+  sudo /usr/bin/tar -xvf "$matcha_file_name" -C "$matcha_directory"
 }
 #安装文件校验
 function matcha_check() {
-  echo "matcha install file check  "
+  echo "[${FUNCNAME[0]}] install file check  "
   if ! sha256sum -c "$current_dir"/$check_file_name; then
-    sudo mv "$current_dir"/"$check_file_name" "$current_dir"/"$check_file_name$(date +%Y%m%d%H%M%S)"
-    sudo mv "$current_dir"/"$matcha_file_name" "$current_dir"/"$matcha_file_name$(date +%Y%m%d%H%M%S)"
-    echo "checked failed!!! please try again"
+    echo "[${FUNCNAME[0]}] checked failed!!! please try again"
     exit 1
   fi
-  echo "file check success"
+  echo "[${FUNCNAME[0]}] file check success"
 }
 
 #新增用户 matcha
@@ -94,7 +92,7 @@ function install_usr_info() {
   local username
   username=$(whoami)
   if [[ ! $username = "root" ]]; then
-    echo "part of the installation process requires root privileges,"
+    echo "[${FUNCNAME[0]}] part of the installation process requires root privileges,"
   fi
   {
     #新增matcha用户
@@ -109,17 +107,27 @@ function install_usr_info() {
 
 #文件权限处理 此操作在完成文件copy 后进行
 function matcha_chown() {
+  echo "[${FUNCNAME[0]}] install directory: $default_install_dir"
   # 设置归属用户组
-  sudo /usr/bin/chown -R "$current_users:$current_groups" $default_install_dir
+  {
+    sudo /usr/bin/chown -R "$current_users:$current_groups" "$default_install_dir"
+  } && {
+    # 添加可执行权限
+    sudo /usr/bin/chmod -R 111 "$default_install_dir"
+  } && {
+    #可执行文件复制至/user/local/bin
+    sudo /usr/bin/cp -f "$default_install_dir/$matcha_exec_file" $default_install_matcha_exec_pre
+    sudo /usr/bin/cp -f "$matcha_log_dir" $default_install_matcha_exec_pre
+  } && {
+    #对于prop配置文件可读 不可写或执行
+    sudo /usr/bin/chmod -R 440 "$properties_file_dir"
+  }
 
-  # 添加可执行权限
-  sudo /usr/bin/chmod -R 111 "$default_install_dir"
+  if [[ "$?" != 0 ]]; then
+    echo "[${FUNCNAME[0]}] install matcha_chown exception, please try again according to the error message "
+    exit 1
+  fi
 
-  #可执行文件复制至/user/local/bin
-  sudo /usr/bin/cp -f "$default_install_dir/$matcha_exec_file" $default_install_matcha_exec_pre
-
-  #对于prop配置文件可读 不可写或执行
-  sudo /usr/bin/chmod -R 440 "$properties_file_dir"
 }
 
 # 复制文件到默认安装位置
@@ -128,9 +136,13 @@ function matcha_file_copy() {
 }
 
 function matcha_env_settings() {
-  echo "export $matcha_work_dir_key=$default_install_dir" >>/etc/profile
-  echo "export $matcha_prop_dir_key=$properties_file_dir" >>/etc/profile
-  source /etc/profile
+  if [[ -z "$(grep -n "export $matcha_work_dir_key" /etc/profile | awk -F '=' '{print $2}')" ]]; then
+    echo "export $matcha_work_dir_key=$default_install_dir" >>/etc/profile
+  fi
+  if [[ -z "$(grep -n "export $matcha_prop_dir_key" /etc/profile | awk -F '=' '{print $2}')" ]]; then
+    echo "export $matcha_prop_dir_key=$properties_file_dir" >>/etc/profile
+  fi
+  . /etc/profile
 }
 
 #安装前置环境处理
@@ -148,18 +160,18 @@ function install_pre_settings() {
 #installing with match shell
 #安装matcha
 function matcha_install() {
-  sudo /usr/local/bin/matcha install core
+  . /usr/local/bin/matcha install core
 
   if [[ $? != 0 ]]; then
-    echo "install failed come back current file"
+    echo "[${FUNCNAME[0]}] install failed come back current file"
     #删除安装文件
-    sudo /usr/bin/rm -rf "$default_install_dir_pre"
+    sudo /usr/bin/rm -rf "$default_install_dir"
 
     if [[ $? != 0 ]]; then
-        echo "file delete failed,please manually"
-        echo "matcha dir: $default_install_dir_pre"
-        echo "matcha file: $default_install_matcha_exec_pre/matcha"
-        echo "matcha file: $default_install_matcha_exec_pre/matcha_log"
+      echo "[${FUNCNAME[0]}] file delete failed,please manually"
+      echo "[${FUNCNAME[0]}] matcha dir: $default_install_dir"
+      echo "[${FUNCNAME[0]}] matcha file: $default_install_matcha_exec_pre/matcha"
+      echo "[${FUNCNAME[0]}] matcha file: $default_install_matcha_exec_pre/matcha_log"
     fi
     sudo /usr/bin/rm -f "$default_install_matcha_exec_pre/matcha"
     sudo /usr/bin/rm -f "$default_install_matcha_exec_pre/matcha_log"
@@ -178,20 +190,16 @@ function matcha_file_download() {
 
 function main() {
   echo "################################################################################"
-  echo "matcha_install for https://github.com/jocker-cn/matcha-shell-util"
+  echo "[${FUNCNAME[0]}] matcha_install for https://github.com/jocker-cn/matcha-shell-util"
   if [[ ! -e $default_install_dir_pre ]]; then
-    echo "The specified installation directory does not exist: $default_install_dir_pre"
+    echo "[${FUNCNAME[0]}] The specified installation directory does not exist: $default_install_dir_pre"
     exit 1
   fi
-
   #安装文件下载
   matcha_file_download
-
   #安装前环境处理
   install_pre_settings
-
   #安装
   matcha_install
 }
-
 main "$@"
diff --git a/src/core/matcha b/src/core/matcha
--- a/src/core/matcha
+++ b/src/core/matcha
@@ -8,7 +8,7 @@
 #工作包路径 一般是安装位置
 matcha_work_dir="${MATCHA_WORK}"
 #matcha 核心模块位置
-matcha_core_work_dir="${MATCHA_WORK}/src/core"
+matcha_core_work_dir="${matcha_work_dir}/src/core"
 
 env_pre="MATCHA-"
 matcha_other_models_dir="$matcha_work_dir/models"
@@ -57,27 +57,31 @@ source /usr/local/bin/matcha_log
 
 #文件格式校验
 function matcha_prop_check() {
-  log_info "matcha $prop_file permissions settings"
-  if [[ -f "$prop_file" ]]; then
-    log_info "matcha create $prop_file"
-    sudo /usr/bin/touch "$prop_file"
-  else
-    local head_line
-    local end_line
-    head_line="$(/usr/bin/cat -n "$prop_file" | /usr/bin/grep -n "$matcha_head" | /usr/bin/awk -F ':' '{print $1}')"
-    end_line="$(/usr/bin/cat -n "$prop_file" | /usr/bin/grep -n "$matcha_end" | /usr/bin/awk -F ':''{print $1}')"
-    if [[ $head_line = "" ]] || [[ $end_line = "" ]] || [[ ! $head_line < $end_line ]]; then
-      $matcha_head >"$prop_file"
-      $matcha_end >>"$prop_file"
-    fi
+  local head_line
+  local end_line
+  head_line="$(/usr/bin/cat -n "$prop_file" | /usr/bin/grep -n "$matcha_head" | /usr/bin/awk -F ':' '{print $1}')"
+  end_line="$(/usr/bin/cat -n "$prop_file" | /usr/bin/grep -n "$matcha_end" | /usr/bin/awk -F ':' '{print $1}')"
+  if [[ $head_line = "" ]] || [[ $end_line = "" ]] || [[ ! $head_line < $end_line ]]; then
+    echo "$matcha_head" >"$prop_file"
+    echo "$matcha_end" >>"$prop_file"
   fi
 }
 
 #配置文件校验
 function matcha_prop_set() {
-  log_info "matcha $prop_file permissions settings"
+  log_info "[${FUNCNAME[0]}] set $prop_file "
   #权限修改
-  sudo /usr/bin/chmod 660 "$prop_file"
+
+  if [[ ! -f "$prop_file" ]]; then
+    log_info "[${FUNCNAME[0]}] create $prop_file"
+    sudo /usr/bin/touch "$prop_file"
+  fi
+
+  if ! sudo /usr/bin/chmod 660 "$prop_file"; then
+    log_error "[${FUNCNAME[0]}] file: $prop_file 'chmod' failed"
+    exit 1
+  fi
+
   #文件格式校验
   matcha_prop_check
 }
@@ -95,7 +99,7 @@ function prop_loop() {
   local key_pre=$2
   #配置模块key完整名称
   local mode_name
-  log_info "matcha install model directory: $abs_model"
+  log_info "[${FUNCNAME[0]}] install model directory: $abs_model"
   if [[ ! -d "$abs_model" ]]; then
     abs_model="$matcha_core_work_dir"
     key_pre=$matcha_core_model_key_pre
@@ -104,20 +108,20 @@ function prop_loop() {
   for file in $(/usr/bin/readlink -f "$abs_model/**"); do
     if [[ -d "$file" ]]; then
       #模块key名称设置
-      mode_name="$key_pre-$(${file##*/} | tr '[:lower:]' '[:upper:]')"
+      mode_name="$key_pre$(echo "${file##*/}" | tr '[:lower:]' '[:upper:]')"
       #遍历模块中的controller 如果不存在则直接跳过
       #如果模块中存在多个controller则只取第一个
-      log_info "matcha deal with $mode_name"
+      log_info "[${FUNCNAME[0]}] deal with $mode_name"
       for file_name in $(/usr/bin/readlink -f "$file/*controller*"); do
         if [[ -f "$file_name" ]]; then
           prop_set "$mode_name=$file_name"
           if [[ ! -x "$file_name" ]]; then
             /usr/bin/chown +x "$file_name"
           fi
-          log_info "matcha $mode_name installation is complete"
+          log_info "[${FUNCNAME[0]}] $mode_name installation is complete"
           break
         else
-          log_warn "matcha $mode_name executable[*controller*] does not exist"
+          log_warn "[${FUNCNAME[0]}] $mode_name executable[*controller*] does not exist"
         fi
       done
     fi
@@ -162,22 +166,25 @@ function matcha_install_models() {
 
 function matcha_install_post() {
   #文件权限修改
-  sudo /usr/bin/chmod 440 "$prop_file"
-  log_info "matcha model installed"
+  if ! sudo /usr/bin/chmod 440 "$prop_file"; then
+    log_error "[${FUNCNAME[0]}] file: $prop_file 'chmod' failed"
+  fi
+  log_info "[${FUNCNAME[0]}] ${#exec_args[1]} installed"
 }
 
 #matcha 安装模块  (处理core和第三方models)
 function matcha_install() {
-  log_info "matcha install start"
+  log_info "[${FUNCNAME[0]}] install start"
   matcha_install_pre
-  if [[ "${#exec_args[@]}" = 0 ]] || [[ "${#exec_args[0]}" = "core" ]]; then
-    log_info "matcha core model installation"
+  if [[ "${#exec_args[@]}" = 1 ]] || [[ "${#exec_args[1]}" = "core" ]]; then
+    log_info "[${FUNCNAME[0]}] core model installation"
     matcha_install_core
   else
     #第三方模块暂不处理
     matcha_install_models "${exec_args}"
   fi
   matcha_install_post
+  log_info "[${FUNCNAME[0]}] Install Successfully!!!"
 }
 
 #设置模块可执行文件路径
@@ -188,20 +195,20 @@ function init_abs_path_exec_file() {
   fi
   #配置文件不存在
   if [[ -z "$prop_file" ]] && [[ ! -e "$prop_file" ]]; then
-    log_error "matcha prop file not exist"
+    log_error "[${FUNCNAME[0]}] prop file not exist"
     exit 1
   fi
   #从配置文件中 获取执行文件路径
   exec_file=$(grep "$prop_file" -e "${model_key}" | awk -F '=' '{print $2}')
   if [[ -z "$exec_file" ]]; then
-    log_error "matcha the current model install failed: $model "
+    log_error "[${FUNCNAME[0]}] the current model install failed: $model "
     exit 1
   fi
 }
 
 #可执行文件初始化
 function exec_file_init() {
-  log_info "matcha schedule model file: $exec_file"
+  log_info "[${FUNCNAME[0]}] schedule model file: $exec_file"
   if [[ -z $exec_file ]]; then
     init_abs_path_exec_file
   fi
@@ -217,7 +224,7 @@ function mode_exist() {
   local model_name=$1
   #模块名称为空
   if [[ -z "$model_name" ]]; then
-    log_error "matcha schedule model require not empty string"
+    log_error "[${FUNCNAME[0]}] schedule model require not empty string"
     exit 1
   fi
   #请求组合模块
@@ -247,13 +254,13 @@ function request_args() {
 
   model=${args[0]}
 
-    # 安装模块
+  # 安装模块
   if [[ "$model" = "install" ]]; then
     matcha_install
     exit 0
   fi
 
-  log_info "matcha schedule request: $model"
+  log_info "[${FUNCNAME[0]}] schedule request: $model"
   #模块是否存在
   mode_exist "$model"
   #初始化文件路径
@@ -266,21 +273,31 @@ function request_args() {
 
 # 脚本执行
 function exec_model_c() {
-  log_info "matcha exec model: $model, exec file: $exec_file request arguments: $exec_args"
+  log_info "[${FUNCNAME[0]}] exec model: $model, exec file: $exec_file request arguments: $exec_args"
   exec $exec_file "$exec_args"
 }
 
 function prop_set() {
-  sudo /usr/bin/sed -i '/'$matcha_head'/a\'"$1"'' "$prop_file"
+  local prop_key_value=$1
+  if ! /usr/bin/grep -q "$prop_key_value" "$prop_file"; then
+    sudo /usr/bin/sed -i '/'$matcha_head'/a\'"$1"'' "$prop_file"
+  fi
 }
 
 function exec_opt() {
-  log_info "matcha start request args: ${args[*]}"
   request_args
   exec_model_c
 }
 
 function main() {
+  log_info "[${FUNCNAME[0]}] request args: ${args[*]}"
+
+  if [[ -z "${matcha_work_dir}" ]]; then
+    log_info "[${FUNCNAME[0]}] work dir is empty: ${matcha_work_dir}"
+    exit 1
+  fi
+
+  log_info "[${FUNCNAME[0]}] work dir: ${matcha_work_dir}"
   exec_opt
 }
 main
